# Privacy Unit

The privacy unit quantifies how much influence an individual may have on your dataset.
OpenDP Polars can reason about the privacy unit in terms of _example-level_ privacy, or _user-level_ privacy.

In [1]:
import polars as pl
import opendp.prelude as dp
dp.enable_features("contrib")

total_working_hours = pl.col.HWUSUAL.cast(int).fill_null(0).dp.sum((20, 60))

## Example-Level Privacy
Attain an example-level privacy guarantee by specifying a bound on how many records an individual may contribute to the data.
The following example obtains this guarantee by setting the privacy unit based on the number of potential **contributions**:

In [2]:
context = dp.Context.compositor(
    data=pl.scan_csv(dp.examples.get_france_lfs_path(), ignore_errors=True),
    # an individual may contribute up to 36 records
    privacy_unit=dp.unit_of(contributions=36),
    privacy_loss=dp.loss_of(epsilon=1.0, delta=1e-8),
    split_evenly_over=4,
    margins=[dp.polars.Margin(max_partition_length=150_000 * 36)]
)
query = context.query().select(total_working_hours)
query.summarize()

shape: (1, 4)
┌─────────┬───────────┬─────────────────┬────────┐
│ column  ┆ aggregate ┆ distribution    ┆ scale  │
│ ---     ┆ ---       ┆ ---             ┆ ---    │
│ str     ┆ str       ┆ str             ┆ f64    │
╞═════════╪═══════════╪═════════════════╪════════╡
│ HWUSUAL ┆ Sum       ┆ Integer Laplace ┆ 8640.0 │
└─────────┴───────────┴─────────────────┴────────┘

Alternatively, you can calibrate to an example-level bounded-DP guarantee
by setting the privacy unit based on the number of potential **changes**:

In [3]:
context = dp.Context.compositor(
    data=pl.scan_csv(dp.examples.get_france_lfs_path(), ignore_errors=True),
    # an individual may change up to 36 records
    privacy_unit=dp.unit_of(changes=36),
    privacy_loss=dp.loss_of(epsilon=1.0, delta=1e-7),
    split_evenly_over=4,
    margins=[dp.polars.Margin(max_partition_length=150_000 * 36)]
)
query = context.query().select(total_working_hours)
query.summarize()

shape: (1, 4)
┌─────────┬───────────┬─────────────────┬────────┐
│ column  ┆ aggregate ┆ distribution    ┆ scale  │
│ ---     ┆ ---       ┆ ---             ┆ ---    │
│ str     ┆ str       ┆ str             ┆ f64    │
╞═════════╪═══════════╪═════════════════╪════════╡
│ HWUSUAL ┆ Sum       ┆ Integer Laplace ┆ 5760.0 │
└─────────┴───────────┴─────────────────┴────────┘

Bounded-DP is a weaker privacy definition than unbounded-DP, as it doesn't protect the total number of records in the data.
In fact, you can consider bounded-DP to be a special case of unbounded-DP, subject to a data invariant.

## User-Level Privacy
Obtain a user-level privacy guarantee by specifying user identifiers in the data. 
In this setting, individuals may make an unbounded number of contributions to the data,
where each row is tied back to individidual via a unique identifier.
Privacy guarantees are based on how many identifiers a user may influence.

In order to make DP releases on this data, 
an additional data truncation preprocessing step is necessary, 
where only a limited number of records corresponding to each identifier are retained.

In [4]:
context = dp.Context.compositor(
    data=pl.scan_csv(dp.examples.get_france_lfs_path(), ignore_errors=True),
    # an individual may contribute data under at most 1 identifier
    privacy_unit=dp.unit_of(contributions=1, identifier="PIDENT"),
    privacy_loss=dp.loss_of(epsilon=1.0, delta=1e-8),
    split_evenly_over=4,
    margins=[dp.polars.Margin(max_partition_length=150_000 * 36)],
)

query = (
    context.query()
    .truncate_contributions(10)
    .select(total_working_hours)
)
query.summarize()

shape: (1, 4)
┌─────────┬───────────┬─────────────────┬────────┐
│ column  ┆ aggregate ┆ distribution    ┆ scale  │
│ ---     ┆ ---       ┆ ---             ┆ ---    │
│ str     ┆ str       ┆ str             ┆ f64    │
╞═════════╪═══════════╪═════════════════╪════════╡
│ HWUSUAL ┆ Sum       ┆ Integer Laplace ┆ 2400.0 │
└─────────┴───────────┴─────────────────┴────────┘

Instead of considering the worst-case of 36 records per individual, 
take into account that it is unlikely to see more than ten records from an individual.
Therefore, truncation introduces some bias by dropping records from individuals who contributed more than ten, but attains a much lower sensitivity.

The same query can be written using SQL-compatible window functions:

In [5]:
query = (
    context.query()
    .filter(pl.int_range(pl.len()).over("PIDENT") < 10) # equivalent to .truncate_contributions(10)
    .select(total_working_hours)
)
query.summarize()

shape: (1, 4)
┌─────────┬───────────┬─────────────────┬────────┐
│ column  ┆ aggregate ┆ distribution    ┆ scale  │
│ ---     ┆ ---       ┆ ---             ┆ ---    │
│ str     ┆ str       ┆ str             ┆ f64    │
╞═════════╪═══════════╪═════════════════╪════════╡
│ HWUSUAL ┆ Sum       ┆ Integer Laplace ┆ 2400.0 │
└─────────┴───────────┴─────────────────┴────────┘

Truncation can also be used to bound contributions per-group. 

This can vastly increase the number of keys released under grouping operations,
and can improve the utility of the gaussian mechanism in cases where individuals make small contributions to many groups.

In [6]:
age_sex = [pl.col.AGE, pl.col.SEX]
query = (
    context.query()
    .filter(pl.col.HWUSUAL < 20)
    .truncate_contributions(1, by=age_sex)
    # this can be slow to compute because it uses a full join, 
    # which is why a filter is used above
    .truncate_partitions(1, by=age_sex)
    .group_by(age_sex)
    .agg(dp.len(), total_working_hours)
)
query.summarize()
query.release().collect()

shape: (9, 4)
┌──────┬─────┬───────┬─────────┐
│ AGE  ┆ SEX ┆ len   ┆ HWUSUAL │
│ ---  ┆ --- ┆ ---   ┆ ---     │
│ f64  ┆ i64 ┆ u32   ┆ i64     │
╞══════╪═════╪═══════╪═════════╡
│ 65.0 ┆ 2   ┆ 14819 ┆ 296090  │
│ 65.0 ┆ 1   ┆ 5933  ┆ 119594  │
│ 47.0 ┆ 2   ┆ 25282 ┆ 506046  │
│ 47.0 ┆ 1   ┆ 5010  ┆ 101728  │
│ 32.0 ┆ 1   ┆ 4933  ┆ 98893   │
│ 20.0 ┆ 2   ┆ 7574  ┆ 151766  │
│ 75.0 ┆ 1   ┆ 183   ┆ 2151    │
│ 20.0 ┆ 1   ┆ 3937  ┆ 78388   │
│ 32.0 ┆ 2   ┆ 15968 ┆ 318295  │
└──────┴─────┴───────┴─────────┘

If you know that individuals may only influence a limited number of partitions ahead of time, 
it is possible to represent this information in the Context.

In [ ]:
context = dp.Context.compositor(
    data=pl.scan_csv(dp.examples.get_france_lfs_path(), ignore_errors=True),
    # an individual may contribute data under at most 1 identifier
    privacy_unit=dp.unit_of(contributions=[
        dp.polars.GroupBound(max_partition_contributions=1),
        dp.polars.GroupBound(by=age_sex, max_influenced_partitions=1),
    ], identifier="PIDENT"),
    privacy_loss=dp.loss_of(epsilon=1.0, delta=1e-8),
    split_evenly_over=4,
    margins=[dp.polars.Margin(max_partition_length=150_000 * 36)],
)

query = (
    context.query()
    .filter(pl.col.HWUSUAL < 20)
    .truncate_contributions(1, by=age_sex)
    .group_by(age_sex)
    .agg(dp.len(), total_working_hours)
)
query.summarize()
query.release().collect()

shape: (9, 4)
┌──────┬─────┬───────┬─────────┐
│ AGE  ┆ SEX ┆ len   ┆ HWUSUAL │
│ ---  ┆ --- ┆ ---   ┆ ---     │
│ f64  ┆ i64 ┆ u32   ┆ i64     │
╞══════╪═════╪═══════╪═════════╡
│ 65.0 ┆ 1   ┆ 6029  ┆ 121731  │
│ 20.0 ┆ 2   ┆ 7729  ┆ 156663  │
│ 20.0 ┆ 1   ┆ 4016  ┆ 80230   │
│ 47.0 ┆ 2   ┆ 25655 ┆ 512814  │
│ 47.0 ┆ 1   ┆ 5105  ┆ 102786  │
│ 32.0 ┆ 1   ┆ 5031  ┆ 100886  │
│ 75.0 ┆ 1   ┆ 163   ┆ 3405    │
│ 32.0 ┆ 2   ┆ 16271 ┆ 325267  │
│ 65.0 ┆ 2   ┆ 15032 ┆ 300614  │
└──────┴─────┴───────┴─────────┘

The recommended best practice is to use the truncation functionality, 
and to set as few distance bounds as possible in the context,
because if you do have an individual with greater influence than is stated in the context,
then their privacy loss will exceed the privacy guarantee.